### ISSUE TITLE
Jikashu Issue

### ISSUE THREAD

**Issue by nikici4re** [eitozx/AkitoBot#1]
C:\Users\gogop\Downloads\AkitoBot-master\main.py:36: RuntimeWarning: coroutine 'BotBase.load_extension' was never awaited
  bot.load_extension(f"extension.{folder}.{filename[:-3]}")
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
C:\Users\gogop\Downloads\AkitoBot-master\main.py:39: RuntimeWarning: coroutine 'BotBase.unload_extension' was never awaited
  bot.unload_extension('extension.fun.tictactoe') # i unloaded this one too, because i had to update some stuff in it, idr that anymore lol       
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
C:\Users\gogop\Downloads\AkitoBot-master\main.py:40: RuntimeWarning: coroutine 'BotBase.load_extension' was never awaited
  bot.load_extension("jishaku")
RuntimeWarning: Enable tracemalloc to get the object allocation traceback

**Comment by eitozx** [comment]
## this issue is NOT related to jishaku. 
This repo is one year old. there has been many updates and the error is just telling that the `unload_extension` function is an async function (which came later after updates).

## discord.py used in this repo is OLD version
( as this repo is one year old)
If you use old discord.py version in which `load_extension` was sync function, it'll be solved.
OR you can simply migrate the code as per latest dpy update.
